'use strict';
const $=id=>document.getElementById(id);
const storyActions=window.storyActions={};
let token='',story=null,items=[],busy=false,dirty=false,createKey=crypto.randomUUID(),uploadRequest=null;
function validPublication(){let first=null;for(const id of ['title','content']){const missing=!$(id).value.trim();$(id).setAttribute('aria-invalid',String(missing));$(id+'-error').textContent=missing?'发布前请填写此项':'';if(missing&&!first)first=$(id);}if(first){first.focus();throw new Error('请填写标题和正文后发布');}}
function directUpload(item){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();uploadRequest=xhr;$('cancel-upload').hidden=false;item.progress=0;render();xhr.open('PUT',item.uploadUrl);xhr.setRequestHeader('Content-Type',item.file.type);xhr.timeout=20000;xhr.upload.onprogress=e=>{if(e.lengthComputable){item.progress=Math.round(e.loaded/e.total*100);render();}};const finish=()=>{uploadRequest=null;$('cancel-upload').hidden=true;delete item.progress;};xhr.onload=()=>{finish();if(xhr.status===200)resolve();else reject(new Error('直传失败：请检查 CORS 和链接有效期；链接过期请移除并重新选图。'));};xhr.onerror=()=>{finish();reject(new Error('直传网络失败，可重试上传。'));};xhr.ontimeout=()=>{finish();reject(new Error('上传超时，可重试上传或移除。'));};xhr.onabort=()=>{finish();reject(new Error('已取消上传，可重试或移除。'));};xhr.send(item.file);});}
async function uploadAndConfirm(item){await directUpload(item);Object.assign(item,await api('/stories/attachments/'+item.id+'/confirm','POST'));delete item.uploadUrl;delete item.file;delete item.error;}
storyActions['cancel-upload']=()=>uploadRequest?.abort();
const feedback=(message,error=false)=>{$('feedback').textContent=message;$('feedback').classList.toggle('error',error);};
async function api(path,method='GET',body=null,extra={}){
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);
  try{const response=await fetch(path,{method,headers:{authorization:token,'Content-Type':'application/json',...extra},body:body==null?null:JSON.stringify(body),signal:controller.signal});
    const result=await response.json();if(!response.ok||!result.success)throw new Error(response.status===409?`${result.errorMsg}。请保留输入后读取最新版本。`:result.errorMsg||'请求未完成，请检查登录或网络');return result.data;
  }finally{clearTimeout(timer);}
}
function controls(){for(const id of ['save','refresh','publish','view','delete','files'])$(id).disabled=busy||!story||story.status==='DELETED';$('publish').disabled=busy||!story||story.status!=='DRAFT';$('create').disabled=busy||!!story;for(const b of document.querySelectorAll('#attachments button'))b.disabled=busy;}
async function run(fn){if(busy)return;busy=true;document.querySelector('main').setAttribute('aria-busy','true');controls();try{await fn();}catch(e){feedback(e.name==='AbortError'?'请求超时，可检查当前笔记状态后重试。':e.message,true);}finally{busy=false;document.querySelector('main').setAttribute('aria-busy','false');controls();}}
function values(){return{title:$('title').value,content:$('content').value,activityPassId:$('activity').value?Number($('activity').value):null,version:story?.version,attachmentIds:items.filter(x=>x.state==='READY').map(x=>x.id)};}
function state(){ $('story-state').textContent=story?`笔记 ${story.id} · ${story.status} · 版本 ${story.version}`:'尚未创建草稿';controls();}
function render(){const root=$('attachments');root.replaceChildren();if(!items.length){const li=document.createElement('li');li.className='empty';li.textContent='尚未关联图片';root.append(li);return;}items.forEach((item,index)=>{const li=document.createElement('li');li.textContent=`${item.name||('图片 '+(index+1))} · ${item.state}${item.error?' · '+item.error:''}`;if(item.progress!=null){const progress=document.createElement('progress');progress.max=100;progress.value=item.progress;progress.setAttribute('aria-label','图片上传进度');li.append(progress);}const action=(label,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',()=>run(fn));li.append(b);};if(item.file&&item.uploadUrl)action('重试上传',async()=>{try{await uploadAndConfirm(item);render();await save();}catch(e){item.error=e.message;render();throw e;}});if(item.state!=='READY')action('重试确认',async()=>{const ready=await api(`/stories/attachments/${item.id}/confirm`,'POST');Object.assign(item,ready);delete item.error;render();await save();});action('上移',async()=>{if(index>0){[items[index-1],items[index]]=[items[index],items[index-1]];render();await save();}});action('下移',async()=>{if(index+1<items.length){[items[index+1],items[index]]=[items[index],items[index+1]];render();await save();}});action('移除',async()=>{if(story.status==='DRAFT'){await api(`/stories/attachments/${item.id}`,'DELETE');story=(await api(`/stories/${story.id}`));}items=items.filter(x=>x.id!==item.id);render();await save();});root.append(li);});}
async function save(){story=await api(`/stories/${story.id}`,'PUT',values());dirty=false;state();feedback('修改已保存');}
async function view(){const data=await api(`/stories/${story.id}`);const root=$('preview');root.replaceChildren();const title=document.createElement('h3');title.textContent=data.title;const content=document.createElement('p');content.textContent=data.content;root.append(title,content);for(const item of data.attachments||[]){const image=document.createElement('img');image.src=item.url;image.alt=`${data.title}的活动图片`;root.append(image);}feedback('已读取真实笔记和短期图片访问链接');}
storyActions['send-code']=()=>run(async()=>{await api(`/user/code?phone=${encodeURIComponent($('phone').value)}`,'POST');feedback('验证码已发送；本地开发请从 Redis 读取。');});
$('login-form').addEventListener('submit',event=>{event.preventDefault();run(async()=>{token=await api('/user/login','POST',{phone:$('phone').value,code:$('code').value});$('token').value=token;feedback('登录成功');});});
storyActions['show-token']=()=>{const visible=$('token').type==='password';$('token').type=visible?'text':'password';$('show-token').textContent=visible?'隐藏令牌':'显示令牌';$('show-token').setAttribute('aria-pressed',String(visible));};
storyActions['use-token']=()=>run(async()=>{token=$('token').value;const user=await api('/user/me');feedback(`已登录：${user.nickName||user.id}`);});
storyActions['create']=()=>run(async()=>{story=await api('/stories/drafts','POST',values(),{'Idempotency-Key':createKey});dirty=false;state();feedback('草稿已创建，可以上传图片。');});
$('edit-form').addEventListener('submit',event=>{event.preventDefault();run(save);});
$('edit-form').addEventListener('input',()=>{dirty=true;});
storyActions['refresh']=()=>run(async()=>{story=await api(`/stories/${story.id}`);$('title').value=story.title;$('content').value=story.content;$('activity').value=story.activityPassId||'';items=(story.attachments||[]).map(x=>({...x,state:'READY'}));dirty=false;render();state();feedback('已读取最新版本');});
$('files').addEventListener('change',()=>run(async()=>{for(const file of $('files').files){if(!['image/png','image/jpeg'].includes(file.type)||file.size>10485760){feedback(`${file.name} 格式或大小不符合限制`,true);continue;}const item=await api(`/stories/${story.id}/attachments`,'POST');item.file=file;item.name=file.name;items.push(item);render();feedback(`正在上传 ${file.name}`);try{await uploadAndConfirm(item);}catch(e){item.error=e.message;}render();}if(items.some(x=>x.state==='READY'))await save();if(items.some(x=>x.error))feedback('部分图片上传失败，请查看图片旁的提示。',true);$('files').value='';}));
storyActions['publish']=()=>run(async()=>{validPublication();await save();story=await api(`/stories/${story.id}/publish?version=${story.version}`,'POST');state();await view();feedback('笔记已发布，订阅信息流正在更新。');});
storyActions['view']=()=>run(view);
storyActions['delete']=()=>{$('delete-confirm').hidden=false;$('cancel-delete').focus();};
storyActions['cancel-delete']=()=>{$('delete-confirm').hidden=true;$('delete').focus();};
storyActions['confirm-delete']=()=>run(async()=>{story=await api(`/stories/${story.id}?version=${story.version}`,'DELETE');items=[];render();state();dirty=false;$('delete-confirm').hidden=true;$('preview').textContent='笔记已删除，图片将在等待期后清理。';feedback('笔记已删除');});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
