# Dot-source this file in the repository root before the isolated acceptance commands.
# It only sets this PowerShell session's environment; no volumes or business data are removed.
$env:MYSQL_HOST_PORT='13307'
$env:REDIS_HOST_PORT='16379'
$env:NAMESRV_HOST_PORT='19876'
$env:BROKER_FAST_HOST_PORT='11909'
$env:BROKER_HOST_PORT='11911'
$env:APP_HOST_PORT='18081'
$env:GATEWAY_HOST_PORT='18080'
$env:MINIO_HOST_PORT='19000'
$env:MINIO_CONSOLE_PORT='19001'
$env:OBJECT_STORAGE_PROVIDER='minio'
$env:OBJECT_STORAGE_ENDPOINT='http://minio:9000'
$env:OBJECT_STORAGE_PUBLIC_ENDPOINT='http://localhost:19000'
$env:OBJECT_STORAGE_BUCKET='citypass-story-files'
$env:STORY_CORS_ORIGINS='http://localhost:18080,http://localhost:18081'
$env:STORY_DEBUG_PAGE_ENABLED='true'
$env:STORY_FILE_UPLOAD_SECONDS='45'
$env:STORY_FILE_READ_SECONDS='3'
$env:STORY_FILE_CLEANUP_GRACE_SECONDS='3'
$env:STORY_FILE_TOMBSTONE_RESCAN_SECONDS='5'
$env:APP_DOCKERFILE='Dockerfile.runtime'
Write-Host 'Isolated citypassfiles ports and short TTLs set for this session. Use only with -p citypassfiles.'
